### ISSUE TITLE
Add testing and automate test running

### ISSUE THREAD

**Issue by thegargiulian** [mashrur-ayon/genderstat#6]
You can use `testthat` to develop tests to ensure that the calculations for the various indices you include are correct and then automate those tests with continuous integration (more [here](https://usethis.r-lib.org/reference/github_actions.html)). 

*This issue is with reference to the JOSS review here https://github.com/openjournals/joss-reviews/issues/5932*

**Comment by mashrur-ayon** [comment]
I have implemented a test using `testthat` as per your suggestion.
