### ISSUE TITLE
Include links to the package on CRAN

### ISSUE THREAD

**Issue by thegargiulian** [mashrur-ayon/genderstat#8]
In the `README` (and the paper), include links to the package on CRAN. You may also wish to expand the installation instructions for individuals who would like to download a development version of the package directly from GitHub.

**Comment by mashrur-ayon** [comment]
As per your suggestion, I have included two separate installations for the CRAN stable release and the GitHub development version. I have also included a badge in the header of the readme file that states the version of the stable release on CRAN. Thank you very much.
